In [3]:
import torch
import pandas as pd
print(torch.__version__)

2.6.0+cu124


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to Tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
# See Tensor dimensions
scalar.ndim

0

In [7]:
# Tensor back as Python int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [2,2]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]

tensor([7, 8])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [1, 2, 3]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 2, 3]])

## Random Tensors


Random tensors are importante because the way many neural networks learn is that they start with tensors full of random numbers and then adjust random numbers to better represent the Data

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(1, 3, 4) # you can change the values as wanted
random_tensor

tensor([[[0.3199, 0.4573, 0.4446, 0.0738],
         [0.7528, 0.0602, 0.3426, 0.8313],
         [0.6412, 0.4142, 0.2883, 0.5605]]])

In [20]:
random_tensor.ndim

3

In [21]:
# Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(3, 224, 224) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones


In [22]:
# Create a tensor off all zeros
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# Create a tensor off all ones
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
# default dtype
ones.dtype

torch.float32

## Create a range of tensors and tensors-like

In [25]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1) # You can remove the start, end and step if wanted
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes


*Note*:  In Pytorch we have 3 main issues between tensors operations

1. Tensors not right datatype
2. Tensors not in right shape
3. Tensors not on the right device

In [27]:
# FLoat 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to float32
                               device=None, # defaults to cpu
                               requires_grad=False) # if True, operations perfromed on the tensor are recorded

float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
tensor = torch.rand(4, 3, dtype=torch.float64)

## Manipulating Tensors (tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplication

In [31]:
# addition
tensor = torch.tensor([4, 5, 6])
tensor = tensor + 10
tensor

tensor([14, 15, 16])

In [32]:
# multiplication
tensor = tensor * 10
tensor

tensor([140, 150, 160])

In [33]:
# and so on...

## matrix multiplication

In [34]:
# Element wise muktiplication
tensor * tensor

tensor([19600, 22500, 25600])

In [35]:
# Matrix multiplication, dot product
torch.matmul(tensor, tensor)

tensor(67700)

In [36]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(67700)
CPU times: user 2.23 ms, sys: 23 µs, total: 2.25 ms
Wall time: 2.2 ms


In [37]:
%%time
torch.matmul(tensor, tensor)  # optimized function

CPU times: user 140 µs, sys: 15 µs, total: 155 µs
Wall time: 162 µs


tensor(67700)

## One of the most common erros in DP: is shape error

There are two main rules when performing matrix multiplication:

1. The **inner dimensions** must have:
* `(3, 2) @ (3, 2)` wont work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(2, 3) @ (3, 2)` -> `(3, 3)`


In [48]:
result = torch.matmul(torch.rand(3, 2), torch.rand(2, 3)) # work

In [43]:
result.shape

torch.Size([3, 3])

In [46]:
result = torch.matmul(torch.rand(3, 2), torch.rand(3, 2)) # wont work

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [47]:
result.T # transpose switches the axes or dimensios of a given tensor, can be used when occurs a shape error at malmul operation

tensor([[1.2208, 0.6366, 1.1557],
        [0.5791, 0.2985, 0.5519],
        [0.4905, 0.2630, 0.4566]])

## Finding the min, max, mean, sum, etc(tensor aggregation)

In [50]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [53]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [52]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [56]:
x = x.type(torch.float32)

In [57]:
# mean requires a tensor of float32 datatype to woek
x.mean()

tensor(45.)

In [58]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

## Findind the positional min and max

In [59]:
x.argmin()  # Find the position(index) of the min item

tensor(0)

In [60]:
x.argmax() # Find the position(index) of the max item

tensor(9)

## Reshaping, stacking, sequeezing and ensqueezing tensors

* Reshaping - reshapes an input tensor to define shape
* View - return a view of a input tensor of ceratin shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permite - Return a view of input with dimensios permuted(swapped) in a certain way

In [72]:
# Lets create a tensor
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [73]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9) # the reshape has to have the same amount of elements of the input tensor
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [74]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [75]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [83]:
# Stack tensors on top of each other
x_stacked =  torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [85]:
# torch.squeeze() remove all single dimensions
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [87]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0) # dim is the index the dimension will be added , you can see in the atributte shape
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [88]:
# torch.permute

x = torch.rand(224, 224, 3)
x_permuted = x.permute(2, 0, 1) # rearraning the index of the dimensions
print(x_permuted.shape)

# x and x_permuted share the same memory, equal to the view() function

torch.Size([3, 224, 224])


## Indexing (selecting data from the tensors)

Indexing with Pytorch is similar to indexing with numpy

In [92]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [93]:
# index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [94]:
x[0][0]

tensor([1, 2, 3])

In [96]:
x[0][0][0]

tensor(1)

In [97]:
x[0][2][2]

tensor(9)

In [98]:
# you can also use ":" to select all of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [104]:
# Get all values of 0th and 1st dimenions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [107]:
# Get all values of 0th dimenion but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

## Pytorch tensors e NumPy

Numpy is a popular scientific Python numerical computing library

and because of this, Pytorch has functionality to intercat with it.

* Data in Numpy, want in Pytorch Tensor -> `torch.from_numpy(ndarray)`
* Pytorch Tensor -> NumPy -> `torch.Tensor.numpy()`

In [112]:
import numpy as np

# Numpy array to Tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [113]:
array.dtype

dtype('float64')

In [114]:
tensor.dtype

torch.float32

In [115]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
numpy_tensor.dtype

dtype('float32')

## Reproducbility (trying to take random out of random)

In short how a neural network works

` start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> again...`

To reduce the randmness in NN and Pytorch comes the concecpt of a **random seed**

In [119]:
x = torch.rand(3, 3)
y = torch.rand(3, 3)

print(x)
print(y)
print(x == y)

tensor([[0.2545, 0.8516, 0.8767],
        [0.9200, 0.9146, 0.6258],
        [0.2362, 0.2826, 0.5981]])
tensor([[0.9927, 0.1784, 0.3911],
        [0.5050, 0.4097, 0.9815],
        [0.8909, 0.8506, 0.0861]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [124]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

x = torch.rand(3, 3)
y = torch.rand(3, 3)

print(x)
print(y)
print(x == y)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


## Running tensors and Pytorch objects on the GPU (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everyhing hunky

### 1. Getting a GPU

1. Easist -  Use Google Colab for free (options to upgrade)
2. Use your own GPU, takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options, use CUDA tutorial in Pytorch documentation
3. Use cloud computinh - GCP, AWS, Azure, etc..

In [127]:
# Check for GPU acess with pytorch
import torch
torch.cuda.is_available()

False

In [128]:
# Setup devide
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [129]:
# Count number of devices
torch.cuda.device_count()

0

## Putting tensors (and models) on the GPU

In [132]:
tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [133]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

## Move tensor back to cpu



In [134]:
# if tensor is on GPU, cant transform it to Numpy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [138]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])